### ISSUE TITLE
I can't see my userId

### ISSUE THREAD

**Issue by dineshmaths1** [voiceittech/voiceit2-nodejs#2]
Hii,
I created new user. But the user Userid is not reflecting my voiceIt USER MANAGEMENT list.
this is my final response  from api
{ message: 'Created user with userId : usr_6d96f6bd44ad49f882add99e6df2b1f1',
  userId: 'usr_6d96f6bd44ad49f882add99e6df2b1f1',
  timeTaken: '0.003s',
  responseCode: 'SUCC',
  createdAt: 1525946493000,
  status: 201 }

**Comment by armaanbindra** [comment]
Hi Dinesh, everything is actually as expected. This is simply because we do not have any user management web console yet for API 2. The User Management page you are referring to is solely for our old API 1.0. API 2.0 is still in Technology Preview and we are in the process of building out a brand new dashboard to manage users, groups and activity for it.

<img width="802" alt="screen shot 2018-05-11 at 8 32 57 am" src="https://user-images.githubusercontent.com/6989720/39926916-4999c9b4-54f6-11e8-8d54-3d670f5ed945.png">
